# hugo server --minify

baseURL = 'http://localhost'
relativeURLs  = true
uglyurls = true

theme = 'book'

disableKinds = ['taxonomy', 'taxonomyTerm', 'category', 'sitemap', 'RSS', '404', 'robotsTXT']

DefaultContentLanguage = 'fr'
#disableLanguages = ['fr']

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Code highlight
#pygmentsStyle = 'monokailight'
pygmentsCodeFences = true

enableEmoji = true

[permalinks]
  docs = "/:title:"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC = 2

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  BookLogo = 'logo.png'

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle = '/menu'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection = 'manual'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/sweitzel/Biet-O-Matic-BE'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath = 'edit/master/documentation/data/content'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'Jan 2, 2006'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch = false

  # (Optional, default none) Search config for flexsearch index.
  # Read documentation at https://github.com/nextapps-de/flexsearch#usage. By default 'balance' preset is used.
  # This option allows to set specific configs for languages support. Must be valid JavaScript object.
  BookSearchConfig = '{ cache: true }'

[languages]
  [languages.fr]
    languageName = "French"
    title = "Documentation"
    weight = 1
  [languages.en]
    languageName = "English"
    title = "Documentation"
    weight = 2
  [languages.de]
    languageName = "Deutsch"
    title = "Dokumentation"
    weight = 3
